# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5a8ac669cbccb73f67a259525af068ceef4ec1caa96ea80aecc75a775392aa4adca332d714ee67b36c8d03c49530501846b6cb563d16498ba55fa3dc4a40302

test:
  secret_key_base: bc3803d427d27d243adc62ba43ba262c117d4ca8f4ee4aa64d16e6f7325aec413aecb55a22ec669e15662b4ebce9729162cd3135337273be9f02cb00008db68e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
